name: Deploy to AKS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group microservices-rg --name msakscluster --overwrite-existing

      - name: Deploy and update images for all services
        run: |
          kubectl apply -f k8s/orders-service
          kubectl set image deployment/orders-service orders-service=msacr.azurecr.io/orders-service:latest
          kubectl apply -f k8s/products-service
          kubectl set image deployment/products-service products-service=msacr.azurecr.io/products-service:latest
